#include <algorithm>
#include <bitset>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <queue>
#include <stack>
#include <string>
#include <tuple>
#include <typeinfo>
#include <vector>